path = r'C:\Users\Tyler_AI\ai-market-cap\ai_earnings_scanner.py'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Build the exact segment from current state
current = "'html+=\'<tr style=\\"background:\'+bg+\'\\"><td><strong><a href=\\"https://finance.yahoo.com/quote/\'+r.ticker+\'\\" target=\\"_blank\\" style=\\"color:#66b2ff\\">\'+r.ticker+\'</a></strong></td>\';html+=\'<td>\'+r.company_name.substring(0,35)+(r.company_name.length>35?\'...\':\'\')+\'</td>\';html+=\'<td><strong style=\\"color:\'+c+\';font-size:1.3em\\">\'+r.score+\'</strong></td>\';html+=\'<td class=earn-cell>\'+r.earnings_date.replace(chr(10),\'<br>\')+\'</td>\';html+=\'<td style=\\"color:\'+(r.days_left==0?\'#ff4444\':(r.days_left<=7?\'#00ff88\':\'#ffcc00\'))+\';font-weight:bold\\">\'+(r.days_left==0?\'Today\':r.days_left+\'d\')+\'</td>\';html+=\'<td data-label=\"Price\">$\'+Math.floor(r.price)+\'</td>\';html+=\'<td data-label=\"3 Day\"><strong>$\'+Math.floor(r.pe_target)+\'</strong> <span style=\"color:#00ff88\">+\'+r.pe_upside+\'%</span></td>\';html+=\'<td data-label=\"7 Day\">$\'+Math.floor(r[\'3d\'])+\' <span style=\"color:#00ff88\">+\'+r[\'3d_up\']+\'%</span></td>\';html+=\'<td data-label=\"14 Day\">$\'+Math.floor(r[\'5d\'])+\' <span style=\"color:#00ff88\">+\'+r[\'5d_up\']+\'%</span></td>\';html+=\'<td>\'+r.analysts+\'</td>\';html+=\'<td style=\\"color:#00ff88\\">\'+r.sb+\'</td>\';html+=\'<td style=\\"color:#58a6ff\\">\'+r.buy+\'</td>\';html+=\'<td style=\\"color:#ffcc00\\">\'+r.hold+\'</td>\';html+=\'<td style=\\"color:#ff6b6b\\">\'+r.sell+\'</td>\';html+=\'<td>\'+fmtMktcap(r.mktcap)+\'</td>\';html+=\'<td style=\\\'color:#fff\\\'>\'+r.short_int+\'%</td>\';html+=\'<td style=\\\'color:#fff\\\'>\'+r.iv+\'%</td>\';html+=\'<td>\'+(r.squeeze?\'<span style=\\\'background:#1a2a1a;border:1px solid #2ea043;border-radius:5px;padding:2px 8px;font-size:0.75em;font-weight:bold;color:#00ff88\\\'>Yes</span>\':\'—\')+\'</td>\';html+=\'<td data-label=\"News\">\'+newsHtml(r.news)+\'</td></tr>\';});tbody.innerHTML=html;};sortBy(\'days_left\');'"

if current in content:
    new = "'html+=\'<tr style=\\"background:\'+bg+\'\\"><td data-label=\\"Ticker\\"><strong><a href=\\"https://finance.yahoo.com/quote/\'+r.ticker+\'\\" target=\\"_blank\\" style=\\"color:#66b2ff\\">\'+r.ticker+\'</a></strong></td>\';html+=\'<td data-label=\\"Company\\">\'+r.company_name.substring(0,35)+(r.company_name.length>35?\'...\':\'\')+\'</td>\';html+=\'<td data-label=\\"Score\\"><strong style=\\"color:\'+c+\'\\">\'+r.score+\'</strong></td>\';html+=\'<td data-label=\\"Earnings\\" class=earn-cell>\'+r.earnings_date.replace(chr(10),\'<br>\')+\'</td>\';html+=\'<td data-label=\\"Days\\" style=\\"color:\'+(r.days_left==0?\'#ff4444\':(r.days_left<=7?\'#00ff88\':\'#ffcc00\'))+\';font-weight:bold\\">\'+(r.days_left==0?\'Today\':r.days_left+\'d\')+\'</td>\';html+=\'<td data-label=\\"Price\\">$\'+Math.floor(r.price)+\'</td>\';html+=\'<td data-label=\\"3 Day\\"><strong>$\'+Math.floor(r.pe_target)+\'</strong> <span style=\\"color:#00ff88\\">+\'+r.pe_upside+\'%</span></td>\';html+=\'<td data-label=\\"7 Day\\">$\'+Math.floor(r[\'3d\'])+\' <span style=\\"color:#00ff88\\">+\'+r[\'3d_up\']+\'%</span></td>\';html+=\'<td data-label=\\"14 Day\\">$\'+Math.floor(r[\'5d\'])+\' <span style=\\"color:#00ff88\\">+\'+r[\'5d_up\']+\'%</span></td>\';html+=\'<td data-label=\\"Analysts\\">\'+r.analysts+\'</td>\';html+=\'<td data-label=\\"Strong Buy\\" style=\\"color:#00ff88\\">\'+r.sb+\'</td>\';html+=\'<td data-label=\\"Buy\\" style=\\"color:#58a6ff\\">\'+r.buy+\'</td>\';html+=\'<td data-label=\\"Hold\\" style=\\"color:#ffcc00\\">\'+r.hold+\'</td>\';html+=\'<td data-label=\\"Sell\\" style=\\"color:#ff6b6b\\">\'+r.sell+\'</td>\';html+=\'<td data-label=\\"Mkt Cap\\">\'+fmtMktcap(r.mktcap)+\'</td>\';html+=\'<td data-label=\\\'Shorts\\\' style=\\\'color:#fff\\\'>\'+r.short_int+\'%</td>\';html+=\'<td data-label=\\\'IV\\\' style=\\\'color:#fff\\\'>\'+r.iv+\'%</td>\';html+=\'<td data-label=\\"Trend\\">\'+(r.squeeze?\'<span style=\\\'background:#1a2a1a;border:1px solid #2ea043;border-radius:5px;padding:2px 8px;font-size:0.75em;font-weight:bold;color:#00ff88\\\'>Yes</span>\':\'—\')+\'</td>\';html+=\'<td data-label=\\"News\\">\'+newsHtml(r.news)+\'</td></tr>\';});tbody.innerHTML=html;};sortBy(\'days_left\');'"

    content = content.replace(current, new, 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print('SUCCESS - all data-labels added')
else:
    print('Segment not found')
    # Find where it is
    idx = content.find("html+='<tr style")
    print(f'Found at: {idx}')
    actual = content[idx:idx+50]
    print(f'Actual start: {repr(actual)}')