"""AI Earnings Scanner — Web Version with Password Auth"""
import os, hashlib, secrets, time, subprocess
from pathlib import Path
from flask import Flask, request, redirect, send_from_directory, abort, make_response, jsonify

# ===== CONFIG =====
import os
PASSWORD_HASH = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" — CHANGE THIS
PASSWORD = os.environ.get("SCANNER_PASSWORD", "trading2026")  # override with Railway env var
SALT = secrets.token_hex(16)
HTML_PATH = Path(__file__).parent / "ai_earnings_web.html"
SCANNER_PATH = Path(__file__).parent / "ai_earnings_scanner.py"
PORT = int(os.environ.get("PORT", 18766))
# Cookie: session token, 24hr expiry
COOKIE_NAME = "scanner_session"
SESSION_TTL = 86400  # 24 hours

app = Flask(__name__)

def hash_pw(pw):
    return hashlib.sha256(pw.encode()).hexdigest()

def make_session():
    token = secrets.token_hex(32)
    expires = int(time.time()) + SESSION_TTL
    return f"{token}|{expires}"

def validate_session(token):
    if not token: return False
    try:
        token_str, exp_str = token.split("|")
        expires = int(exp_str)
        return time.time() < expires
    except: return False

def set_session(resp):
    token = make_session()
    resp.set_cookie(COOKIE_NAME, token, max_age=SESSION_TTL, httponly=True, samesite='Lax')

@app.route("/")
def index():
    token = request.cookies.get(COOKIE_NAME, "")
    if not validate_session(token):
        return send_from_directory(".", "login.html")
    # Serve the latest scan file (generated by ai_earnings_scanner.py), not the static copy
    workspace = Path(__file__).parent
    html_files = sorted(workspace.glob("ai_earnings_57day_*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    if html_files:
        # Read and serve directly to avoid any caching
        with open(html_files[0], 'r', encoding='utf-8') as f:
            content = f.read()
        resp = make_response(content)
        resp.headers['Content-Type'] = 'text/html; charset=utf-8'
        resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        return resp
    return send_from_directory(".", "ai_earnings_web.html")

@app.route("/login", methods=["POST"])
def login():
    pw = request.form.get("password", "")
    if pw == PASSWORD:
        resp = make_response(redirect("/"))
        set_session(resp)
        return resp
    return send_from_directory(".", "login.html")

@app.route("/logout")
def logout():
    resp = make_response(redirect("/"))
    resp.delete_cookie(COOKIE_NAME)
    return resp

@app.route("/scan/latest")
def scan_latest():
    token = request.cookies.get(COOKIE_NAME, "")
    if not validate_session(token):
        abort(403)
    # Find the most recent scan HTML in workspace
    workspace = Path(__file__).parent
    html_files = sorted(workspace.glob("ai_earnings_57day_*.html"), reverse=True)
    if html_files:
        with open(html_files[0], 'r', encoding='utf-8') as f:
            return f.read(), 200, {"Content-Type": "text/html"}
    return "No scans yet", 404

@app.route("/scan/run", methods=["POST"])
def scan_run():
    """Run a fresh scan and return the new HTML"""
    token = request.cookies.get(COOKIE_NAME, "")
    if not validate_session(token):
        abort(403)
    try:
        workspace = Path(__file__).parent
        result = subprocess.run(
            ["python", str(SCANNER_PATH)],
            capture_output=True, text=True, timeout=180,
            cwd=str(workspace)
        )
        # Return the latest scan
        html_files = sorted(workspace.glob("ai_earnings_57day_*.html"), reverse=True)
        if html_files:
            with open(html_files[0], 'r', encoding='utf-8') as f:
                return f.read(), 200, {"Content-Type": "text/html"}
        return jsonify({"error": "Scan completed but no file found", "stdout": result.stdout, "stderr": result.stderr}), 500
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Scan timed out after 180s"}), 504
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    print(f"AI Earnings Scanner Web — http://localhost:{PORT}")
    print(f"Password: {PASSWORD}")
    app.run(host="0.0.0.0", port=PORT, debug=False)